[package]
name = "y2015"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../common" }
md-5 = "0.10.5"
thiserror = "1.0.37"
anyhow = "1.0.80"

[dev-dependencies]
pretty_assertions = "1.4.0"
test-case = "3.3.1"
