[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.26", features = ["derive"] }
dirs = "4.0.0"
reqwest = { version = "0.11.13", features = ["blocking", "cookies"] }
rusqlite = "0.28.0"
