
jobs:

- job: Ruby
  strategy:
    parallel: true
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - command: echo Running Ruby Tests

- job: Python
  strategy:
    parallel: true
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - command: echo Running Python Tests