variables:
  ruby_version: 2.6
  python_version: 3.8

jobs:
- job: Ruby
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UseRubyVersion@0
    displayName: 'Use Ruby $(ruby_version)'
    inputs:
      versionSpec: '>= $(ruby_version)'
  - task: CmdLine@2
    displayName: Install Gems
    inputs:
      script: |
        cd ruby & bundle install

  - task: CmdLine@2
    displayName: Run Tests
    inputs:
      scripts: |
        cd ruby & bundle exec rspec

- job: Python
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python_version)'
    inputs:
      versionSpec: '$(python_version)'
      addToPath: true
      architecture: 'x64'
  - task: CmdLine@2
    inputs:
      script: |
        echo Starting Python Tests