[package]
name = "y2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
common = { path = "../../common" }
nom = "7.1.3"
regex = "1.11.1"
test-case = "3.3.1"
thiserror = "2.0.6"
