name: test-dotnet

on:
  push:
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: |
          cd src/dotnet/
          dotnet test
